version: '3'
services:
  smtp2json:
    container_name: 'smtp2json'
    build:
      context: ./build/
      dockerfile: Dockerfile
    ports:
      -  "25:25"
    volumes:
      - ./:/app
  httpbin:
    container_name: 'httpbin'
    image: kennethreitz/httpbin:latest
    ports:
      -  "80:80"
